% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Oct-2024 17:42:02
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
                                                 

Init = struct;
Init.Instance = 'FSAE_Achilles';
Init.Type = 'CRG_Hockenheim_F';
Init.Chassis = struct;
Init.Chassis.aChassis = struct;
Init.Chassis.aChassis.Units = 'rad';
Init.Chassis.aChassis.Value = [0 0 0];
Init.Chassis.aChassis.Comments = 'Roll-Pitch-Yaw';
Init.Chassis.vChassis = struct;
Init.Chassis.vChassis.Units = 'm/s';
Init.Chassis.vChassis.Value = [10 0 0];
Init.Chassis.vChassis.Comments = '';
Init.Chassis.sChassis = struct;
Init.Chassis.sChassis.Units = 'm';
Init.Chassis.sChassis.Value = [6 0 0.17];
Init.Chassis.sChassis.Comments = '';
Init.Axle1 = struct;
Init.Axle1.nWheel = struct;
Init.Axle1.nWheel.Units = 'rad/s';
Init.Axle1.nWheel.Comments = 'Values are [left right]';
Init.Axle1.nWheel.Value = [42.8761 42.8761 0.2332];
Init.Axle2 = struct;
Init.Axle2.nWheel = struct;
Init.Axle2.nWheel.Units = 'rad/s';
Init.Axle2.nWheel.Comments = 'Values are [left right]';
Init.Axle2.nWheel.Value = [42.8761 42.8761 0.2332];

