% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Nov-2024 09:12:48
%  MATLAB version: 24.2.0.2740171 (R2024b) Update 1
% -------------------------------------------------------------------
                                            

Init = struct;
Init.Instance = 'FSAE_Achilles';
Init.Type = 'Skidpad';
Init.Chassis = struct;
Init.Chassis.aChassis = struct;
Init.Chassis.aChassis.Units = 'rad';
Init.Chassis.aChassis.Value = [0 0 0];
Init.Chassis.aChassis.Comments = 'Roll-Pitch-Yaw';
Init.Chassis.vChassis = struct;
Init.Chassis.vChassis.Units = 'm/s';
Init.Chassis.vChassis.Value = [1 0 0];
Init.Chassis.vChassis.Comments = '';
Init.Chassis.sChassis = struct;
Init.Chassis.sChassis.Units = 'm';
Init.Chassis.sChassis.Value = [-25 0 0];
Init.Chassis.sChassis.Comments = '';
Init.Axle1 = struct;
Init.Axle1.nWheel = struct;
Init.Axle1.nWheel.Units = 'rad/s';
Init.Axle1.nWheel.Comments = 'Values are [left right]';
Init.Axle1.nWheel.Value = [4.2876 4.2876 0.2332];
Init.Axle2 = struct;
Init.Axle2.nWheel = struct;
Init.Axle2.nWheel.Units = 'rad/s';
Init.Axle2.nWheel.Comments = 'Values are [left right]';
Init.Axle2.nWheel.Value = [4.2876 4.2876 0.2332];

