% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Oct-2024 18:34:47
%  MATLAB version: 9.14.0.2674353 (R2023a) Update 7
% -------------------------------------------------------------------
                                                    

Maneuver = struct;
Maneuver.Type = 'WOT_Braking';
Maneuver.Instance = 'FSAE_Achilles';
Maneuver.Brake = struct;
Maneuver.Brake.t = struct;
Maneuver.Brake.t.Value = [0 11 11.2 190 191 200];
Maneuver.Brake.t.Units = 'sec';
Maneuver.Brake.t.Comments = '';
Maneuver.Brake.rPedal = struct;
Maneuver.Brake.rPedal.Value = [0 0 0.7 0.7 0 0];
Maneuver.Brake.rPedal.Units = '0-1';
Maneuver.Brake.rPedal.Comments = '';
Maneuver.Steer = struct;
Maneuver.Steer.t = struct;
Maneuver.Steer.t.Value = [0 11 11.2 100 150 200];
Maneuver.Steer.t.Units = 'sec';
Maneuver.Steer.t.Comments = '';
Maneuver.Steer.aWheel = struct;
Maneuver.Steer.aWheel.Value = [0 0 0 0 0 0];
Maneuver.Steer.aWheel.Units = 'rad';
Maneuver.Steer.aWheel.Comments = '';
Maneuver.Accel = struct;
Maneuver.Accel.t = struct;
Maneuver.Accel.t.Value = [0 1 1.2 10 10.2 200];
Maneuver.Accel.t.Units = 'sec';
Maneuver.Accel.t.Comments = '';
Maneuver.Accel.rPedal = struct;
Maneuver.Accel.rPedal.Value = [0 0 0.0875 0.0875 0 0];
Maneuver.Accel.rPedal.Units = '0-1';
Maneuver.Accel.rPedal.Comments = '';

